---
- name: Add EPEL repo
  yum:
    name: epel-release
    state: latest

- name: Add IUS repo
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: latest

- name: Update all installed packages
  yum:
    name: "*"
    state: latest
