version: '3.5'

services:
  coexist-server:
    build:
      context: ./centos7-systemd-sshd
    container_name: coexist-server
    hostname: coexist-server
    ports:
      - "9000:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp:exec
    networks:
      coexist:
        ipv4_address: 172.24.1.10

  coexist-app:
    build: coexist-basic
    container_name: coexist-app
    hostname: coexista-app
    ports:
      - "9001:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp:exec
    networks:
      coexist:
        ipv4_address: 172.24.1.11

networks:
  coexist:
    name: coexist
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.1.0/24
