---
comanage_db_password: "changethispassword"
comanage_proxy_db_password: "changethispassword"
ldap_password: "changethispassword"
client_ldap_password: "changethispassword"
test_organization_password: "changethispassword"

https_cert:
  # Note: this is a real private key for a real live domain (scz-vm.net)
  # This domain has no records or hosts defined, and will only ever be used
  # for local testing.  Therefore, publishing the private key does not have
  # any security impact.
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAtXKT7VLRUENSWX2/YzCnnHCir0/jDA8GGhC2WDi8HinpGQAm
    Lg+4t+R9A/8NvfVXaYiuMBgT+Ozq74qEThkVFdMeGwuoRoBqdAFWajkoNpiqxDTN
    lr+j4H/qNo0DKKr36odOKSbHyDy/t/7fD9s9VZkAcb8Zav3nhQA3y/9Akq+tyuUe
    emjlw3jmMF5jLDIEx+/zvo4FOcTNaBN47H1F4FOpH9iJMUpi+SH2fWjt1mD7yL1e
    GKYWVGxj977MUxM2ZKkDJR9T+0+NPQWbhfi4TPtmtAyMrIh88WzB7WEwC3DD5Btk
    avlHpV2eiIHpFFTMCB9oH4enR9lDEulOLSiDHwIDAQABAoIBACVc1Zcd4ZoMcs2Y
    tis/npP5IZbF9XPLOC9v14xtClePu775J+N+O0QqmY+UGolOFtTVX0DqBFrStkHj
    HQFT6uKWmXFqQhlaYhFHITs4T86GO0uxr8/l4GHfFSRsfwUFx40UlYSlxqe10qiZ
    o+cI9yVEHzJM7nf4lo7tj4/DHNHXYEf5D0gge9CaG+pjsGszjW8zVKG0FtemKWrG
    2HHhYUQxE6fx9NmFV0W/xYChl1XneIN8ap9Ppw6YwYmDw1ldWR+Ii+3eZeVfxlbv
    RvttaedxZmwzYvkYBC8fWee7qpkMnFSYqnd9nS7Hc8FRoNeuBIvjrmDnQGQ3UB7+
    vyWikEkCgYEA2OvunVd6OkbaMuKT6gojjJZj1BBROL4YqRoUN5iXZdSKFRLnw0Hr
    43yopHF0IajuXZZD8l5gSeIoNXlg1dmX/kWazisS3a5e31b7JL5hw6upDMp7Wizk
    anukW6Z2ktfNwPjEHxP+aqgwtqAMbNaW7RiYojpaN6tZ0GTMPx/N/K0CgYEA1iKk
    MFb4r+e51i4jMw9aR85IKE+yRQEgUBHRvfJgZkkq9EQTHN2NfZZnsU5s4NOSU+4z
    3/Fk69/5K/cpiEaDw/OLa0eq7EKgcRE+KKXagF2mZAzHcrjMNRPjNB5nmd5OSMNL
    mmXyGvTawXXQ5gzIZRfaMq1RYOaUzUGIJEW4DHsCgYEAjaQYzcJ1/CGRjpJmNPbj
    2YPFsY3qCxwNbDWsJ9VKXmKWu0X58YRU69jVIXM3elcdNhzNRzAavYOf77LO6TRI
    y+5VM/PqQLgAGONp38c0fRjUrJZ2Tx5rE6CiZHngiOfC4RNOtGBQywIBtO3yzwqb
    yDs8RwnFKP6JCcsXlsxEq40CgYAwhH7RGROVv5pCpgeBrSvWcy20PIJ20g+BNNhi
    AkXHRzK9T6NI+gXx+58Y9F0E/8r6y1Djn60vKHsrc//sCZYXUto2/3EBwQLbO33q
    9dExHobxyldybd6O9CeZin4MxerU37MEk66sXuglx00CosjQ5vugWdbDbtsuOnff
    SBCwewKBgQC6NQS/rDxdhsLEG4uu3bgTsxqrAS9EkaeoFGZn9LSIOwWkf6E+mmqZ
    UaOAQqRpIlZ7Eu+nsnD0fBXgFFU1Ss+BT7Bjzh5wTFF8+jAXp/lE9I+zcFO9ScpI
    209ynRSUPP/EeAV4Fz0KrfXEDHcr7mFlIUsMYt8zmleIY6uOn/weVA==
    -----END RSA PRIVATE KEY-----
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIFHzCCBAegAwIBAgIQAagDaB3h0PgGpxwGFyCYdTANBgkqhkiG9w0BAQsFADBk
    MQswCQYDVQQGEwJOTDEWMBQGA1UECBMNTm9vcmQtSG9sbGFuZDESMBAGA1UEBxMJ
    QW1zdGVyZGFtMQ8wDQYDVQQKEwZURVJFTkExGDAWBgNVBAMTD1RFUkVOQSBTU0wg
    Q0EgMzAeFw0xNzEyMTUwMDAwMDBaFw0yMDEyMjMxMjAwMDBaMF4xCzAJBgNVBAYT
    Ak5MMRAwDgYDVQQHEwdVdHJlY2h0MRMwEQYDVQQKEwpTVVJGbmV0IGJ2MREwDwYD
    VQQLEwhTZXJ2aWNlczEVMBMGA1UEAwwMKi5zY3otdm0ubmV0MIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtXKT7VLRUENSWX2/YzCnnHCir0/jDA8GGhC2
    WDi8HinpGQAmLg+4t+R9A/8NvfVXaYiuMBgT+Ozq74qEThkVFdMeGwuoRoBqdAFW
    ajkoNpiqxDTNlr+j4H/qNo0DKKr36odOKSbHyDy/t/7fD9s9VZkAcb8Zav3nhQA3
    y/9Akq+tyuUeemjlw3jmMF5jLDIEx+/zvo4FOcTNaBN47H1F4FOpH9iJMUpi+SH2
    fWjt1mD7yL1eGKYWVGxj977MUxM2ZKkDJR9T+0+NPQWbhfi4TPtmtAyMrIh88WzB
    7WEwC3DD5BtkavlHpV2eiIHpFFTMCB9oH4enR9lDEulOLSiDHwIDAQABo4IB0TCC
    Ac0wHwYDVR0jBBgwFoAUZ/2IIBQnmMcJ0iUZu+lREWN1UGIwHQYDVR0OBBYEFCzj
    Lw6n1Mu17dhL+shDrNbxFhLeMCMGA1UdEQQcMBqCDCouc2N6LXZtLm5ldIIKc2N6
    LXZtLm5ldDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
    AQUFBwMCMGsGA1UdHwRkMGIwL6AtoCuGKWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNv
    bS9URVJFTkFTU0xDQTMuY3JsMC+gLaArhilodHRwOi8vY3JsNC5kaWdpY2VydC5j
    b20vVEVSRU5BU1NMQ0EzLmNybDBMBgNVHSAERTBDMDcGCWCGSAGG/WwBATAqMCgG
    CCsGAQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMAgGBmeBDAEC
    AjBuBggrBgEFBQcBAQRiMGAwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2lj
    ZXJ0LmNvbTA4BggrBgEFBQcwAoYsaHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29t
    L1RFUkVOQVNTTENBMy5jcnQwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOC
    AQEAw2F28r10Cz2V5TllZkU8c60eWW4R/Cn1u3A025pOXCRo3F8b9WctGdvZiAzz
    /z+liQnjhcKYnYORbGXEdmZTxJqLtLF77BtO2pMZi1JSdtbqhTn6HHPZSlABRhXD
    Ofz3e6tgDNdGTszib3En3zXvExPdj2rmjHAPLxN0Xosxc1MN/76bLsx2zDw9GbWJ
    atnqDcweHVJY/4oog9ZJ+UHDsJ5K2KdFhlnPuIMyxFm2syfJnwC3wUbXstKoBPiJ
    EbNREnSRYwoafEmalsUzormVsJ77ApW93jrhebnVkenL8QlmFr+rSw04CreJyMqV
    mtwm0SBFZTNL4bpopiKd+5iDOQ==
    -----END CERTIFICATE-----
  chain: |
    -----BEGIN CERTIFICATE-----
    MIIE+zCCA+OgAwIBAgIQCHC8xa8/25Wakctq7u/kZTANBgkqhkiG9w0BAQsFADBl
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
    d3cuZGlnaWNlcnQuY29tMSQwIgYDVQQDExtEaWdpQ2VydCBBc3N1cmVkIElEIFJv
    b3QgQ0EwHhcNMTQxMTE4MTIwMDAwWhcNMjQxMTE4MTIwMDAwWjBkMQswCQYDVQQG
    EwJOTDEWMBQGA1UECBMNTm9vcmQtSG9sbGFuZDESMBAGA1UEBxMJQW1zdGVyZGFt
    MQ8wDQYDVQQKEwZURVJFTkExGDAWBgNVBAMTD1RFUkVOQSBTU0wgQ0EgMzCCASIw
    DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMV2Dw/ZQyk7bG3RR63eEL8jwnio
    Snc18SNb4EweQefCMQC9iDdFdd25AhCAHo/tZCMERaegOTuBTc9jP8JJ/yKeiLDS
    lrlcinQfkioq8hLIt2hUtVhBgUBoBhpPhSn7tU08D08/QJYbzqjMXjX/ZJj1dd10
    VAWgNhEEEiRVY++Udy538RV27tOkWUUhn6i+0SftCuirOMo/h9Ha8Y+5Cx9E5+Ct
    85XCFk3shKM6ktTPxn3mvcsaQE+zVLHzj28NHuO+SaNW5Ae8jafOHbBbV1bRxBz8
    mGXRzUYvkZS/RYVJ+G1ShxwCVgEnFqtyLvRx5GG1IKD6JmlqCvGrn223zyUCAwEA
    AaOCAaYwggGiMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMHkG
    CCsGAQUFBwEBBG0wazAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQu
    Y29tMEMGCCsGAQUFBzAChjdodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGln
    aUNlcnRBc3N1cmVkSURSb290Q0EuY3J0MIGBBgNVHR8EejB4MDqgOKA2hjRodHRw
    Oi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVkSURSb290Q0EuY3Js
    MDqgOKA2hjRodHRwOi8vY3JsNC5kaWdpY2VydC5jb20vRGlnaUNlcnRBc3N1cmVk
    SURSb290Q0EuY3JsMD0GA1UdIAQ2MDQwMgYEVR0gADAqMCgGCCsGAQUFBwIBFhxo
    dHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMB0GA1UdDgQWBBRn/YggFCeYxwnS
    JRm76VERY3VQYjAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYunpyGd823IDzANBgkq
    hkiG9w0BAQsFAAOCAQEAqSg1esR71tonHqyYzyc2TxEydHTmQN0dzfJodzWvs4xd
    xgS/FfQjZ4u5b5cE60adws3J0aSugS7JurHogNAcyTnBVnZZbJx946nw09E02DxJ
    WYsamM6/xvLYMDX/6W9doK867mZTrqqMaci+mqege9iCSzMTyAfzd9fzZM2eY/lC
    J1OuEDOJcjcV8b73HjWizsMt8tey5gvHacDlH198aZt+ziYaM0TDuncFO7pdP0GJ
    +hY77gRuW6xWS++McPJKe1e9GW6LNgdUJi2GCZQfXzer8CM/jyxflp5HcahE3qm5
    hS+1NGClXwmgmkMd1L8tRNaN2v11y18WoA5hwnA9Ng==
    -----END CERTIFICATE-----

client_idp_users:
  # baas/baas
  baas: '{SHA256}/B8qagQ/Ek9twLaWgkzDY/WLFsyk0rsmEeHjwmVM3q8='
  # student/student
  student: '{SHA256}JkyMOBvxbJgqTlmw3UxveAjFGgX2TDXbQsx4oqcodbs='
  # employee/employee
  employee: '{SHA256}L9wBdwV9OlxsLAgh4B9PqNkPmju3r9grDbUmr5jWjeg='

#Google Backend
google_client_id: "changethisclientid.apps.googleusercontent.com"
google_client_secret: "CHANGETHISSECRET"

# ORCID Backend
orcid_client_id: "changethisclientid.ORCID"
orcid_client_secret: "CHANGETHISSECRET"

#Microsoft Backend
ms_client_id: "changethisclientid.apps.msusercontent.com"
ms_client_secret: "CHANGETHISSECRET"

# SAML signing cert for clients
client_saml_cert:
  priv: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDDFKgHyzsPmuPw
    0cFblaoAv8Uo2za/+nxfcKqd8Pm1pNI1ePIZGbTahv6ktqz0O44z0k8k/3Glnb/c
    UqO3fNcDXpAh8YJ6pX+GnS4+jizYi66i5KCDpLu15uGXccDyqDL8Lwd9UkBqKPVE
    CWc5Cjf/OD/YjW5kaVugtjJ0qCiFfEAtwdWIbcrIBDXDAe+2XMy4RUT3dLH9i6Di
    kzrVcxKXcVHNQrtEkKhSz5f/jXovIOGv3zhmS4ne/Xjh3CDLGO9p3pNqzoFBvOQb
    JrrJx8HkfC+riHLVdHaq5kDz2BiKFO/JtuCTazcowjYgZ6Rov6eRiTQA/DcN87tw
    kUH5hIc5AgMBAAECggEBAIQdmS6uFHGdFIIjjC/aTCf1uDDTRWD+4vw/8UzFxlee
    KD7Oiic1oaXdhtdGYBuHueaep7sGxJDFJQqxbO73PSarBDH4vcUSECu6h3cWEokV
    EFCBRbPh/L5UfrNx9ppgDyd7MjdNXRKIapKJS771jLbsAVFHd1vJfqR4v/MBb2/2
    Z01a9LPvIn8gotRTQ78I8i91KrSVUj5ZZ4j7phXbi2LDhABRmsr1UbhhFwWDgUwz
    B0liDQCkezhE71/RzfFVGgCoFaTSy4IxRkxczYbF8aQ1TkirkL6a3r9I1BkEOSy4
    Q3KXB9hCIMx3G/Zzf24g1aoV8CJnVwd5nJENp96fb4ECgYEA4OoSXLtx0/MvVPEC
    bvneXvuvqGx5cF6c0Wi5bhltL0erubdZ/hSYmgeMWo9sXh7MFVIYwTS6SXgU6OpO
    jQTEfwVWlfOyzg8Uo9fE9792tEk7QP9qnUVDqORKPIOtQlC2gTpEFUTJJWxwYlwk
    JyZKNcaiIi/McbT/voS7Aa9BrCcCgYEA3gsCVRe2nuSvxKUFFfLefadQ/Bgtmtb5
    qoxKHdhAwkh81YaOslFIjEbothv/G/kkg0wAqTJjr7eQqZhOvmR9WTIhm+/0G4tF
    FmEUdjz2GnfGo7+IL2QC3GQBPCr/W5I7RSdh2IISJNjKTbCcJEl4j3IOmePgoLeK
    wlnIQ7nibZ8CgYAbJycgWuDbHbjRIGeSzkeyX+BNDQt8LW/xOBtq11b/Jj/tI92R
    dxsVPWQMatRCaKVqzYZ/jMYQqJadp+vjyneOfi592/XyOo/bV+lHn63NBipJJozQ
    f9QzR5xOwfbg0q213Drr9mnyQq0ussEKmOzMoTZhujOMZrWZYpzRDz92cQKBgQDG
    5jG2q8FI4C2bBv9hQ+eNw11GFRp1A3EuFvElftuzrV81no0gqrNEBRjcWIPTOQA+
    JMzKw3qMovCRGwAeiMHILqHwn6eZLM48V8YOjFkgKH7lm+KQIRR2+5YnoZSRIJK7
    RaXeXdWG8DN4GGYmEzJNvKvbqkdDcGZ55hcAo/hynQKBgFgzZs+reOw6xQja5etv
    ZBt+MKrQlFWgQPwR8qmWGWZ02wrR9XEP3QRny470WBpJ8NFfTOREvSikoi26qWn0
    HIqN1SZp6waSCRXQ1G+5npdG9Cpy0g1/kUVc1kcGgWwwYGOeeWYvGQrPMskpRmlo
    UgcNlD/szshy7RRfuRW+2are
    -----END PRIVATE KEY-----
  pub: |
    -----BEGIN CERTIFICATE-----
    MIIDYDCCAkigAwIBAgIJANmp2CfNHjkZMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
    BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
    aWRnaXRzIFB0eSBMdGQwHhcNMTgwMjI2MTQ1OTA0WhcNMjgwMjI2MTQ1OTA0WjBF
    MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
    ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
    CgKCAQEAwxSoB8s7D5rj8NHBW5WqAL/FKNs2v/p8X3CqnfD5taTSNXjyGRm02ob+
    pLas9DuOM9JPJP9xpZ2/3FKjt3zXA16QIfGCeqV/hp0uPo4s2IuuouSgg6S7tebh
    l3HA8qgy/C8HfVJAaij1RAlnOQo3/zg/2I1uZGlboLYydKgohXxALcHViG3KyAQ1
    wwHvtlzMuEVE93Sx/Yug4pM61XMSl3FRzUK7RJCoUs+X/416LyDhr984ZkuJ3v14
    4dwgyxjvad6Tas6BQbzkGya6ycfB5Hwvq4hy1XR2quZA89gYihTvybbgk2s3KMI2
    IGekaL+nkYk0APw3DfO7cJFB+YSHOQIDAQABo1MwUTAdBgNVHQ4EFgQUCBFdf80k
    xJ9JkJ48RqtpZvu1SrkwHwYDVR0jBBgwFoAUCBFdf80kxJ9JkJ48RqtpZvu1Srkw
    DwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAPpqZooSulmZdL1ps
    i2m2XTR2kf4Mww3x9z3hUH9sR0+/2tuP7U9ODarSK6ac1YSE6/B3f/7nefwdMF9p
    t78abBHLCpWsmUUXkaiGcMFH3CRliCuCBI/12K2Q8YxCCHXACdpYTkilmEIBdqRU
    DAyqyeVt2u/YWgZualZx6yHIffPqG/iy7HVaffLy/W3DKwC9x12kHyUiTJzfZCeB
    wI05NBtSpgXSuEopT1RjCbPey9YweOJ2jPJYtNmBOz65/PVm00WnRgjqwBmjzDQC
    ticXKu1TjM0zKFF19VmlsX68x5L32v1BUz2r3W5SrvwNN//rxGrbVsMGmgup7eOc
    XKaNuw==
    -----END CERTIFICATE-----


# Satosa metadata signing key
satosa_metadata_cert:
  priv: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDS7Ik3opUBaJXf
    siOyJTQ9xd1vyiQpiyIZRXB5lB9Tcsqd31BswaU7eBT13Bsn2VUVRc/42sPDzMnq
    fmy109C4CpIM3DatWTauBvU9WL75XQhqRJtOlA+lnJEQVa5XHbmxRXs7PmDhSWDz
    qhkTBMzzyMOU+XV1C/sGEEoZ5CSpyO0bSAajzH+CQ71TOAqE3smflrggSvXH+DxR
    5/BpL8sYNFCJ3IUutlIni3mTnLe4uiKNVzlnBZ8fXlHf6lVWAIJFiNOqAjsa8QZr
    5jhXK4G0rkL9jfxhoVqwuNuIU374zVkXkRXvAXdLBWc25JrWkLVkBaQWUDox309L
    NGcvI6gXAgMBAAECggEBANAQFKuU7XeeO3mWuC+bE5V8AZusw09XuCNFpFXKD7y5
    l7Vz/FnMC7pGEicVIJSGhq+dVjIdWs9izCtM2t/iOhnSE5AsCqOlRZMVugTx7jD9
    3Lc3RhyVYXn0oASFAJ1e7TY5W/5s4hRZ1hGG0YU5TxOMD6J9EaiMUOsCVpaDvsbb
    afwYv6gVUsXr9AjGHrygEAWZUiXEX0+rHEGrQ17XsKB9sW6EOlLUVk2cfOsFMRn0
    xPiqYdFzDAS4GdBDp7Zrf/MN7TTC7VECAO2mp+vOEqJzZiGBHAQYP/XlGUiw4zBg
    HfSlNHxLp8vELuwxojpj+3ec6fQz5z/zEetHgueJH0ECgYEA9wNAsLbNvuDxIC7U
    LPXPWh4ycjOcTOSCyoYxLyiYIGqA3DFok1CfRXhcO/vdsu+wf3NKaloy2xvVkGH9
    bACGelsk9UzgkdDpwc8LACyEK/Va8R0vJrGL2PEqP4tnzSYQ9wp7UiTZlrfHAVTE
    4bq9vRtrXQkPwpWXRXT6s+6GrYsCgYEA2pkkdzektW8+LEgt2rJjLVY1IqtNWka7
    YHLCrZI3vnoyewt7SoKCuQsbTejWMQtqAndpTWdHrBCySwqvtQ4PFpa7zyWpHQ+t
    i3LqJmKDGZ46eyKVRPzz4Qv6o4lQg6lZhMjNwN6GZFTZ/uybiCX38rGeKvrCdxae
    EmWRfZduGSUCgYEAiWS4xdJYbLSnylPh1sQ/OowTWSxV4vszuLydfPKic11qIZAl
    79LnVHfXLdIxhYcG8E1Ldg6HvRIlXzLyB/He2w35Z6wEOXcvnoqwPr+EIQNPO1AV
    Wvtkox25dzDuYtCqnQ6qe41drhS4z4e8HyaExTwMIuqYZo5YXtzrWcvyA3MCgYBh
    qBTQZb1hiMb/xWcm0pbYBDFMwbaW5A6Fsf8ix7W7lJ/EtIZp7RA1Vq7mCWTXGEBN
    xcb3W3J7fiIIwEdq3VMERma0ziBU6VIggD/20f+7jCKYLAT/gvn4yf842/lqOFfT
    qFmzFjZ30ChraIy7MCsq8wq0LL5/sU0A7vsmXmZDOQKBgQCGf/AZ9VcAaq9nKjkZ
    9ZUFDOHuxWF4qhppy6yNlfVlWiixjR1qqZWdHZ+GkMEkqPwKlbcLdiDPq1nAg5gp
    UQXPiaFK+mLaO7+6uTMBsiX6BMZRtvdT7YQyoU6ADkB9AqZp3d72kZC0tlUZTXg+
    HeIbsb5+TNbh96K23NkZpH1qqw==
    -----END PRIVATE KEY-----
  pub: |
    -----BEGIN CERTIFICATE-----
    MIIDIDCCAgigAwIBAgIJALtj5xVgUd6/MA0GCSqGSIb3DQEBCwUAMCUxCzAJBgNV
    BAYTAlhYMQowCAYDVQQIDAEgMQowCAYDVQQKDAEgMB4XDTE4MDIyNjE1MDE1NFoX
    DTI4MDIyNjE1MDE1NFowJTELMAkGA1UEBhMCWFgxCjAIBgNVBAgMASAxCjAIBgNV
    BAoMASAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDS7Ik3opUBaJXf
    siOyJTQ9xd1vyiQpiyIZRXB5lB9Tcsqd31BswaU7eBT13Bsn2VUVRc/42sPDzMnq
    fmy109C4CpIM3DatWTauBvU9WL75XQhqRJtOlA+lnJEQVa5XHbmxRXs7PmDhSWDz
    qhkTBMzzyMOU+XV1C/sGEEoZ5CSpyO0bSAajzH+CQ71TOAqE3smflrggSvXH+DxR
    5/BpL8sYNFCJ3IUutlIni3mTnLe4uiKNVzlnBZ8fXlHf6lVWAIJFiNOqAjsa8QZr
    5jhXK4G0rkL9jfxhoVqwuNuIU374zVkXkRXvAXdLBWc25JrWkLVkBaQWUDox309L
    NGcvI6gXAgMBAAGjUzBRMB0GA1UdDgQWBBT4+xwD25C6fN6uR/QCsDF0eB7LxjAf
    BgNVHSMEGDAWgBT4+xwD25C6fN6uR/QCsDF0eB7LxjAPBgNVHRMBAf8EBTADAQH/
    MA0GCSqGSIb3DQEBCwUAA4IBAQADuhzNzhPOcHE4AV889SKwZx0Sgmli900ECRRR
    k5Wrn7W+QUfFn6I37DLxJu07Zac5xxWJE2glHfXxB2Bwyf0XjIBYDxjSFKNf7ziO
    To/ZPvWdPtd+yWMZ+Fp45GInnTznmkckcNtzhQfUpCJ4rLmwzKdWCQNnk/AAHH6a
    wBs+CbXzmXEGO7e0uk0m5i6INoO6Ij/8wty9XY+cCETPvCHUu99YZL0Bh8F/63UM
    +gWYLIuYGBWmI1bu5l3j6A8Bu+4UFW5SJ1jNrnU9XnCOnJU5nH35qmE0IdctWPmx
    EEQqzGJodBhxL7VNunP/pOHtpkRSOm2Jx7WQ1CliYOxVHT4p
    -----END CERTIFICATE-----


# Satosa SAML signing keys
satosa_frontend_cert:
  priv: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmYtAVshhVQYB7
    GYo9YNq0SsVYEj1k/bgENRN84xCkaCHaTCvyiGKC3VmXLKeJg+7qYQhhsY3Ai3j+
    JFqjSSoZ6di34pgw3Vh8GuFcbexpf+k8bHgxW/pe8bmI/jLDl9SlfQmVWvqqKCM3
    6zinWLHl1hpK/dqmbyqJPsTf0gSZtFZHINDBredqrq0kfpjyR7aoUjNeDd5fMglC
    DyZd491JWTc6/zfExZ67zZtVdKrornADQPAla4RbS7DA8aD6YfHt15rdHbQnBnSP
    +HAgcQ02R/BIeTmGhsYMioPpJzi31OJQYBGMa+gI3VUBhsFegtWK4YDaF721kZ0h
    cpVUHzARAgMBAAECggEABll9AWbzgMVoJsp5uQ/qKLk1wL+pciIwlJCF9t0fdHa4
    3ADOKIpF4CKcWaWNmzTauD0NudSxyShJbMFsaBDRt31yFMpj7nF0AABymzlirUAB
    YZnuGEwfSOJGp1C0FTzFE6+q3vVC3Z18gpTKa7B50YCTLktzvag+YlBv6O612Du2
    zpzUOYgluHyYtq3r1+dcYZsAkzdK8ZtVQXS9x3Jl+g8FQnsvOaWg5MXl3auN1tu2
    S/7cdHQQ1PQmuFUlofRRnNKtH01R4aZAL1Xj/d+ljzGJBufGaGlJspNU1RrRsIbZ
    ycQYwZAeNHtY49hl+NyhdNUJmfBeuV/h1UEPUcRZtQKBgQDXx5TKsUIE+wCoQXd8
    bAyVTE7TGuFzafXPhHi5YsHeABJG0bFEeHlR5tOlxeqJ2uLddChH0ejnh9sVeWoQ
    lG6uwoYPPrB02v3G4pjJLJEXJqEql6PlHI1oskrHa08w478mwexR26s2T3zQi508
    9JB6E4a9dBleQ2YZvL3qTVN83wKBgQDFZk0xHtDjFn4YNFaXRVB+gnX/65FT1che
    glJvaxhvOGNcwhtQDXbtswO4ZOpLY2nNwJ82rOsxwaGRTRIPNfLls20wHLFMGFQ8
    gq6jzbtf6rCtsZHyByBaMYHRiGwqSb4UwBuqo6nkVJlkGG3IqSSVQHCFeT1144WR
    ZxIqYQIBDwKBgBuT7nhZX06zpcnbVCIazSDnt8tTTC0sBbaX/7Xx4UU2TR+v/S/7
    FcZZ8gLl4KvtxcD3743+Tf4JZv6/ncawsdS0F94q7PKCapzYqR5NC94hmcePyeqm
    U4xl/RivpldhRDT34/QyVxeB4TnmHhqER1LS3A2qoPNjOdFgRgWEDH+RAoGAenpy
    FLMxGmV/UVdQDsXEHuqlemfYIPM5QmKL8XO6km+jPw900OO50dxLx6JduO7y2+XT
    I6KAv7uLmtL+DJAFqL3+VmbHHxbNVUokP6BLzUSZ4PuXOVtwmGW1TaPesRJWLRvR
    TrwDkpdnITMDEwjXmP+FkVtbZgUIf+I65C6ShsMCgYBWy0h6NUl8hQ6Qbplta04G
    bboSPKX9J+LZUcXOu1vVxR4KoAVxerD2Uoi9e8dNDuQlpKipDTnWSVDYoQizNWb/
    MdwsKPHDbhO/abhlWl/TGkgo7tJ3ImxUE/NixqPIasUgMwuN2XOy3YJQcPLMEiy1
    5qnkwKlfYbJHA812NHdwSw==
    -----END PRIVATE KEY-----
  pub: |
    -----BEGIN CERTIFICATE-----
    MIIDIDCCAgigAwIBAgIJAOu4gMd3M7LTMA0GCSqGSIb3DQEBCwUAMCUxCzAJBgNV
    BAYTAlhYMQowCAYDVQQIDAEgMQowCAYDVQQKDAEgMB4XDTE4MDIyNjE1MDIzMloX
    DTI4MDIyNjE1MDIzMlowJTELMAkGA1UEBhMCWFgxCjAIBgNVBAgMASAxCjAIBgNV
    BAoMASAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmYtAVshhVQYB7
    GYo9YNq0SsVYEj1k/bgENRN84xCkaCHaTCvyiGKC3VmXLKeJg+7qYQhhsY3Ai3j+
    JFqjSSoZ6di34pgw3Vh8GuFcbexpf+k8bHgxW/pe8bmI/jLDl9SlfQmVWvqqKCM3
    6zinWLHl1hpK/dqmbyqJPsTf0gSZtFZHINDBredqrq0kfpjyR7aoUjNeDd5fMglC
    DyZd491JWTc6/zfExZ67zZtVdKrornADQPAla4RbS7DA8aD6YfHt15rdHbQnBnSP
    +HAgcQ02R/BIeTmGhsYMioPpJzi31OJQYBGMa+gI3VUBhsFegtWK4YDaF721kZ0h
    cpVUHzARAgMBAAGjUzBRMB0GA1UdDgQWBBQjliHlXaIerPEJquCiraqTOJ7uATAf
    BgNVHSMEGDAWgBQjliHlXaIerPEJquCiraqTOJ7uATAPBgNVHRMBAf8EBTADAQH/
    MA0GCSqGSIb3DQEBCwUAA4IBAQARKD7AhvQcx7hHFJDrXyLQ+sdSh/zL33/fyXeT
    1qbjpMtke4BVfibCRJNs+cds4v6SPAxdgRobnpW9CeiBQRIoGfPmrdFu/q7IqaH1
    pQTVa0cgW0pzt6A4RrE6OUs2mNdKV8dvtEFwL7gt4iQLNdqflHDulMXK36BvJ5qR
    7QJljY64lwn15CtuGMIEdolMeK2RuKy+OceM7nkZUqlLJqEyJ7N5EynH82KIMCgk
    2TabDtFmIi8kTsSZ/tuFeRNs+lDduJpxnZPV/IFdHhjLTf1V6SUjZI95LcCWh0Nq
    2tWMfGVIoj03kC6YDaX8L6GNo4CmXM2eQV/UMCkEcCUkBMZf
    -----END CERTIFICATE-----

satosa_backend_cert:
  priv: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnwRvRJjjQRgun
    4ZUelzyw3peyd0h1AwWtDm5bpF5GXB+V2WXZ39eDR+/avJ242cUvew8th+ahJavN
    e5O/NHv1go6KDVxCJQIUf2bGdyC4Ykbqhv7fX3Zigs4WK0SbPiq6BSLSI5M/+YDT
    0kLyjQ0CAdU2wWCVTnI9N7YLr65mcSCvTNbadE5sBBHwjs/vyOEyWydFDroXbNpe
    GTh32m8DlUkUQb7xjabYP+AL71ewPml3ata3PtDCfQoNfgcICg1gn1hy1kCqqCRl
    khTTrnIQRwJNpOPHBR6vCkz+7ppYzVWi6dB4gm/7u6xX3d3lc409BQ9KEsKE28ho
    0mQQQ/GBAgMBAAECggEAK/Eypyua8DuY7AX0OMom9LGqDO6gBT6gav9/uvOoWkfh
    YjBLNLIk0teyJZsIuZYZx+E1TZjuucGTakT3o7tMyTfEvLbZNt5Y2COzOUOVR5c+
    ukpYUwy/hvh6oWX+F6hGKuoTf/YfqT9jFplaPgzinmb6gdhPw2yEEjMYtaD0TxLg
    ijulPDG7N/l2/f5sU78nt/+vIsyHaV76qBy9Gtzh9xpKZIaEjK7SzIU1Cte2DPKV
    ZL7WstY27sZlF+Cn7U9/TfY8ax37V8jHUu0keIv3SMMvmouyvRV6yNWdVVOvByM4
    4Ohi/mWogzTIaQTuErCOkLC1PGBi7WcOjTqxhdEAAQKBgQDQNjVpE3Ms97Agc1xa
    SQIM63tcnZksiBfHg4Ft9L3YcTdDpRmcHBKVytFbdPhArrlJ1Uho/7zZtoUQaAv6
    QVh0Vu2zxfkWJba/IX8aV8VlAkIt6WkwbiehjgcS8czo30zbVIYAlNeQJXS/vwkh
    imwEF2fUrKCpxZ+EjUtkY7KUAQKBgQDOQcOVr2YQ68fIZhOpK8mYkMniJhW1UVIu
    JF+NrQAnJaM8pHRtKzxpqArsy9znyJ65E4oQCtqfTYDjI7ZDBxgBq7z4kRdY3s2H
    oNoJiQMEERGiRnLjCj5+1tUsy4wDTR55QqozIlWTwZ568CreNlXw42oNCqtTXtt0
    c9poN4NdgQKBgQDAPazmzZyEIlUuQRU+DzajczC9fI2Wvjkmb1crjNNUaoQaIvAY
    YRsPzumqRb+JCUnuz8xBlg5p/cmyMj8M2xSupixm1h17w2qN4oGWcv/AmWs9NMt4
    edyBn78MUNFfGf2+bLYlB0hYwRygheQKYeIFjQ7DIHhfCCaWnlbD5AFYAQKBgAhr
    /wR5qP0/42R3Zo4dz5l/L/8f9vr0WxqvOYebbMosa0HqpSZgAZN+3RNWL6r3MiP0
    fEqzZsHidETSDHsoKv7GeGzd38otLs8+7ig9g/YCjGnH3qEOpgaf1wyBMzJfT8M7
    yZ9U45Go8kOq0tVH+rJfVtE5gk1hLizPHjfrLF4BAoGBAKqFtNSyMT5S49Me/3Ao
    wfJBfs56POYw1wUtz36oUl3XMvBIrpOGcbkz4AVvYcuTc3jxL3x2y+cNjdSiL0z9
    IoC0NQMUaRawf4RSVX/h17UscxA/PYKl4bf0oE6L1ejsRKw9nb8gWuqQmAiowgPW
    4aTCUygPQK/iA8i+bAURqydF
    -----END PRIVATE KEY-----
  pub: |
    -----BEGIN CERTIFICATE-----
    MIIDTjCCAjagAwIBAgIJAIbqDargWdh4MA0GCSqGSIb3DQEBCwUAMDwxGjAYBgoJ
    kiaJk/IsZAEZFgpzY3otdm0ubmV0MQwwCgYDVQQLDANTQ1oxEDAOBgNVBAMMB2Jh
    Y2tlbmQwHhcNMTgwNTE1MTAwMzE2WhcNMTkwNTE1MTAwMzE2WjA8MRowGAYKCZIm
    iZPyLGQBGRYKc2N6LXZtLm5ldDEMMAoGA1UECwwDU0NaMRAwDgYDVQQDDAdiYWNr
    ZW5kMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp8Eb0SY40EYLp+GV
    Hpc8sN6XsndIdQMFrQ5uW6ReRlwfldll2d/Xg0fv2ryduNnFL3sPLYfmoSWrzXuT
    vzR79YKOig1cQiUCFH9mxncguGJG6ob+3192YoLOFitEmz4qugUi0iOTP/mA09JC
    8o0NAgHVNsFglU5yPTe2C6+uZnEgr0zW2nRObAQR8I7P78jhMlsnRQ66F2zaXhk4
    d9pvA5VJFEG+8Y2m2D/gC+9XsD5pd2rWtz7Qwn0KDX4HCAoNYJ9YctZAqqgkZZIU
    065yEEcCTaTjxwUerwpM/u6aWM1VounQeIJv+7usV93d5XONPQUPShLChNvIaNJk
    EEPxgQIDAQABo1MwUTAdBgNVHQ4EFgQUfgf81jf+mw2zoL1qNJEAc2PTEpMwHwYD
    VR0jBBgwFoAUfgf81jf+mw2zoL1qNJEAc2PTEpMwDwYDVR0TAQH/BAUwAwEB/zAN
    BgkqhkiG9w0BAQsFAAOCAQEAVD6h/EABjHhYlNwKRNsmT7l7laYBETCTQnGBLpGd
    2Pq8myJK2JEcC2ohdTHxPjtcetP6FlyV4VEhQevL7SQp6dKOW+9OwjDpCt9Z68kW
    5+7uz3H+1gVlyI9+bdIFduUSMMBzai0yXWrO/R7OI0dkgYZHO+WwF330OAj1sCNE
    8qLkyEk4QDJ5CTvSydNCQKcueell0ZBIY7GXtARx9z/NSA9pEUPyVB/WPf7j/QRG
    iQz6svdR01Es8/cX/x3KFR/xLs+gsGdFKjD0S6aCNbrzIIGUR9Uic+P3Tm/HBXWF
    e4DP2nHvJyqySyT1sU52VfctCT/kY8iR6eyxw1zqvzsi7Q==
    -----END CERTIFICATE-----
