---
- include_vars: "modules.yml"

- name: Ensure necessary paths are available.
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ module_paths }} "

- name: Ensure that packages are installed
  yum:
    name: "{{ packages }}"
    state: present
  become: Yes

  #- name: Copy module configurations
  #  template:
  #    src: "{{ item }}.conf.j2"
  #    dest: "{{ module_dest }}/{{ item }}.conf"
  #  with_items: "{{ modules }}"

- name: Enable modules
  apache2_module:
    state: present
    name: "{{ item }}"
  become: yes
  with_items: "{{ modules }}"
